services:
  pocketbase:
    build: .
    ports:
      - "8090:8090"
    volumes:
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_migrations:/pb/pb_migrations
      - pb_data:/pb/pb_data
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pb_data:
